CREATE BITMAP INDEX XP_JRF_MESSAGE_1
 ON JRF_MESSAGE(THREADID, INTIME)
 ;
 
CREATE BITMAP INDEX XP_JRF_MESSAGE_2
 ON JRF_MESSAGE(INTIME)
 ;

CREATE INDEX XP_JRF_SUBSCRIBE_1
 ON JRF_SUBSCRIBE(USER_NAME)
 ;
 
CREATE BITMAP INDEX XP_JRF_SUBSCRIBE_2
 ON JRF_SUBSCRIBE(USER_NAME, THREADID)
 ;
 
 
CREATE INDEX XP_JRF_FORUM_1
 ON JRF_FORUM(GROUPID)
 ;

CREATE BITMAP INDEX XP_JRF_FORUM_2
 ON JRF_FORUM(FORUMID, LOCKED)
 ;

CREATE INDEX XP_JRF_THREAD_1
 ON JRF_THREAD(FORUMID)
 ;

CREATE INDEX XP_JRF_THREAD_2
 ON JRF_THREAD(lintime)
 ;

CREATE BITMAP INDEX XP_JRF_THREAD_3
 ON JRF_THREAD(THREADID, lintime)
 ;

CREATE BITMAP INDEX XP_JRF_THREAD_4
 ON JRF_THREAD(THREADID, lintime, SORTBY)
 ;
 
